### ISSUE TITLE
Preview Content

### ISSUE THREAD

**Issue by Baramus** [ustwo/ustwo.com-frontend#123]

**Comment by daaain** [comment]
Related to https://github.com/ustwo/ustwo.com-backend/issues/61

Had a chat about this with @andydutch and the team the other day, a possible solution could be to use the built in WP draft functionality and return the data for posts with draft state on the slug URL, but not in the index / search endpoints. This way it's possible to see and share the URL on the live site, but without it coming up for visitors.

**Comment by andydutch** [comment]
Potential solution...

* Preview content gets added to staging site and previewed there
* Have the ability to publish to live from staging
* Linked to update action on live (WP) site to update staging and keep staging up to date

**Comment by voylinux** [comment]
Looks like you can make some kind of aouth authentication from the frontend app and get posts with draft state.
I am building a somehow similar solution to your frontend app and just noticed I will also not have this funcionality.

**Comment by matthewedwards12** [comment]
preview with blog posts is effectively covered by publishing to a date far in the past and setting a password. Using the origin site is also helpful to avoid waiting for CDN purge before seeing additional last-minute tweaks to a post
