### ISSUE TITLE
Join Us redesign

### ISSUE THREAD

**Issue by collingo** [ustwo/ustwo.com-frontend#165]
- [x] Make decision as to if this is a quick fix (no back-end) or if it requires back-end dev
- [ ] Get estimate from Andy (Elementary) for time to implement
- [ ] Make final decision if we do full back-end implementation
- [x] Implement front-end UI as per Gyppsy designs

**Comment by matthewedwards12** [comment]
Designs by Gyppsy available

**Comment by phil-linnell** [comment]
Design implemented. Need solution to split wordpress modules apart in order to have the job listing below the page blurb and above the perks grid

**Comment by kater1** [comment]
Will go with full back-end solution (not quick fix)

**Comment by kater1** [comment]
@phil-linnell please can you link to the UI in this ticket - thanks :)

**Comment by phil-linnell** [comment]
Branch is: features/new-join-us-layout

UI is nearly done - aim to get sign off from Gyppsy today.

**Comment by phil-linnell** [comment]
@kater1 What do you mean link to the UI?

**Comment by phil-linnell** [comment]
![screen shot 2015-11-12 at 11 07 10](https://cloud.githubusercontent.com/assets/6968080/11116957/f940e6e6-892d-11e5-9f6a-2bc0c3bab0de.png)
