### ISSUE TITLE
Review animations

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#182]
Right now animations are a bit disjointed on the blog index and non-existent on blog posts (which will be the landing page for a good part of visitors), I think with a bit of work we could make these shine.

But actually it would be good to review animations site wide, for example we aren't making good use of the fact that we can actually have smooth transitions between pages!

Here's the prioritised list we came up with Ben and Grant:

Broken
----------

 - [x] No rollover animations: links, what we do items
 - [ ] Blog post page transition in – looks broken for a second while data is loading
 - [ ] Work item page transition in – images load abruptly
 - [x] Blog transition in – nicer maybe centred loader, build up

Needs love
----------

 - [ ] Rollover for logo to make it clear it's going home
 - [ ] Something looping to focus on the chevron animation – also to serve as a quasi loading indicator
 - [ ] Blog categories drop down animation

Nice to have
----------

 - [ ] Mobile menu transition in
 - [ ] Contact tray to animate in a nicer way

 - [ ] Blog search in line animation
 - [ ] Newsletter icon to animate in on scroll
 - [ ] Orienting page transition between blog index and post pages

 - [ ] General page transition out
 - [ ] 404 interactive dick around game / easter egg

**Comment by matthewedwards12** [comment]
closing this, as Grant is working on separate tickets covering most of these
