### ISSUE TITLE
Implement video module

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#187]
We have the video modules available in WP, but they are not implemented yet on the frontend.

So right now the inline embedded videos are fixed to whatever the default size is, see: https://ustwo.com/what-we-do/monument-valley

A simple solution could be to have a fixed 4:3 aspect ratio (with negative padding) full width container implemented in CSS.

**Comment by matthewedwards12** [comment]
Long lost issue! Definitely needs a fix as soon as possible.
