### ISSUE TITLE
Review markup

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#192]
Oscar highlighted a bunch of issues, like:

  * too many `<section>`s everywhere
  * we shouldn't have lots of `<h1>`s like in the footer
  * no `alt` on images
  * ustwo logo also has no content and a bad `title`
  * `<hr>` shouldn't be used when it's decorational only: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr

More from the man himself:
`h3` on ustwo News doesn’t make sense either

oscar [5:43 PM]
maybe in the home does

oscar [5:44 PM]
but being the first element on the `footer` makes me think that it doesn't

oscar [5:44 PM]
I’m just trying to help here BTW

oscar [5:44 PM]
I didn’t have half a proper look at our structure until now

oscar [5:57 PM] 
I can pinpoint some more stuff

oscar [5:57 PM]
i.e. the social links at the footer don't have content

oscar [5:57 PM]
and the `title` is not okay

oscar [5:59 PM]
the Get in Touch modal can’t be properly accessed via keyboard

oscar [5:59 PM]
its close `button` has no content

oscar [6:00 PM]
and has quite a few `h1`

oscar [6:00 PM]
`article` use there is doubtful

**Comment by phil-linnell** [comment]
Picked off low hanging fruit, corrected some mistakes regarding H tags, changed some <sections> to <div>, added <title> to svgs and alt to <img>.
