### ISSUE TITLE
Blog page additional designs

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#232]
![blog overview desktop](https://cloud.githubusercontent.com/assets/69962/11338013/5a1a13b6-91e9-11e5-97ce-75292bcfe8ce.png)
![blog overview mobile](https://cloud.githubusercontent.com/assets/69962/11338012/5a1928c0-91e9-11e5-9bdf-e9c02c3cae72.png)

**Comment by daaain** [comment]
Requires back end work to flag a blog post as featured

**Comment by kater1** [comment]
Story needs breaking down

**Comment by matthewedwards12** [comment]
Some info

https://drive.google.com/a/ustwo.com/folderview?id=0B5YUpSnTZn51OUxidk5rendOQzg&usp=sharing
