### ISSUE TITLE
Homepage design rethink

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#233]

**Comment by kater1** [comment]
Linked to and blocked by #146

**Comment by daaain** [comment]
Might worth looking at refactoring Hero component while doing this, see #246.

**Comment by matthewedwards12** [comment]
@applesmoke this is one you could work with @phil-linnell on.

**Comment by matthewedwards12** [comment]
@andydutch and @applesmoke could you chat about implementing a carousel-style image changer for the home page? I think we'd work with two – one to illustrate client work, and one to illustrate ventures and own IP stuff.

need to think about how a visitor cycles back and forth and what they can click through to... amongst other stuff!

**Comment by matthewedwards12** [comment]
underway w/c 22 Aug. No overview ticket needed
