### ISSUE TITLE
Video in Hero module

### ISSUE THREAD

**Issue by phil-linnell** [ustwo/ustwo.com-frontend#248]
(from the whiteboard)

- [x] Adapt hero module to take video
- [x] Back-end update to include video link and fallback image in data
- [x] Implement fallback for mobile

**Comment by daaain** [comment]
This is for example the Join Us page video Ben has done

**Comment by daaain** [comment]
Maybe also do a quick investigation if streaming via Vimeo or Youtube API is better / easier

**Comment by collingo** [comment]
This is more or less done, I just need to test that it works well with the data integration. At the moment the staging api responses are not updating which I suspect is a matter of flushing the CDN. Will talk to @daaain to confirm
