### ISSUE TITLE
As a user I want to be able to share content via the native Facebook app

### ISSUE THREAD

**Issue by phil-linnell** [ustwo/ustwo.com-frontend#254]
As a user
I want to be able to share content via the native Facebook app
So that there is continuity of the user experience on the phone

**Scenario 1:**

Given I haven't previously set a preference for handling Facebook links
And the Facebook app is installed
And I am on my mobile
When I tap the Facebook sharing button
Then the Facebook app is offered as a choice to share the content with

**Acceptance Criteria**

 - [ ] Can I share content to Facebook in the native app, if it is installed, or if not can I share through the browser YES  / NO

**Comment by collingo** [comment]
I've had a look into this and it looks troublesome.

If we set the link to open in the FB app, if the app isn't install the link simply won't work. There is a nasty hack to provide a web link as a fallback but I wouldn't say it's the most reliable of approaches. If we just opt for the web link as we currently have, at least it will always work.

Most phones have a built in share functionality built into the browser so, for that reason, I would suggest this is not such an important issue.

**Comment by collingo** [comment]
Deleting as team agreed we do not need anything more than the current web sharing option for desktops. Mobiles have their own in built sharing option which should be sufficient.
