### ISSUE TITLE
Rollover animation

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#266]
Currently we don't have any rollover animation, but we should at least have ones for text links and work / blog item blocks

**Comment by daaain** [comment]
Not sure if we have anything designed for the text links, might need to get a VD help with that

**Comment by phil-linnell** [comment]
Ben Marsh consultation:

- SVG animation for work items
- blog post slight scale of image
- blog post underline link text goes same colour
- fade futura text 75% (same for join-us studio tabs)
- footer 'google maps' underlines go white
- homepage, underlines invert, e.g. white to black (with transition)
- close X to coral colour in tray
- join us jobs, slide in 3px top

- UI fix, make subscribe button text same size as Get in touch

**Comment by phil-linnell** [comment]
Fix for #283 is in this branch features/rollover-states
