### ISSUE TITLE
Blog post page transition in

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#267]
We should make sure that the page looks nice even while we are loading data / rendering content

- [ ] UI assets from Ben M / Danson
- [ ] Implement assets

Fixes #302

**Comment by daaain** [comment]
We could use this as a study for a nice generic page transition in which can be applied elsewhere.

**Comment by phil-linnell** [comment]
Related: I, Phil Linnell, see the footer for a split second when I go to a case study page from what-we-do. Why is this? Ethel does not (both on Chrome). My original thought is that the main page content does not have an explicit height where the footer does. Then, some React sorcery unbeknownst to me delays the rendering of the page content, thus seeing the footer only for that split second.

**Comment by phil-linnell** [comment]
Ben Marsh is looking into a loading overlay

**Comment by phil-linnell** [comment]
Added a transition out + got Gyppsy's eyes on it and got sign off
