### ISSUE TITLE
Polish and publish Sandbox

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#273]
Make sandbox look nice and publish it in a way that a build is hosted somewhere and publicly accessible.

Inspiration:
* http://styleguide.cfapps.io/index.html
* https://github.com/trulia/hologram

**Comment by daaain** [comment]
Just had a chat with Nick, now that I actually got sandbox working in live environments, we're going to do a minimum viable increment on this with just enough formatting that it looks good enough to be shared. We'll also update the README to make sure that it's clear how to develop with it.

We can come back to making it a proper style guide later, but that work only pays if we make it part of the design process.

**Comment by andydutch** [comment]
Not a priority for the foreseeable future, closed.
