### ISSUE TITLE
Get in touch slider disappears on mobile 

### ISSUE THREAD

**Issue by fffabs** [ustwo/ustwo.com-frontend#298]
When tapping on the Get in Touch button on the footer, the slider will simply flash and then disappear without the possibility of clicking on the button for a second time. Only seen this happening on Safari for iOS on my iPad Mini 4, with iOS 9.1 installed.

**Comment by phil-linnell** [comment]
Hi @fffabs thanks for posting this issue.
However, we can't replicate this - I'm using the setup you mentioned. Are there possibly any other conditions that could help us replicate it? e.g. Can you replicate from cold start on the homepage or after navigating around? Is it consistent? Thanks again.

**Comment by andydutch** [comment]
Issue suspected to be linked to an ad-block.
