### ISSUE TITLE
Add studio clocks

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#31]
### User Story

AS A visitor
I WANT to know what the local time is each ustwo studio globally

### Acceptance Criteria
- Can the visitor view the local time of the relevant studios? YES

----

### Implementation Task List

- [ ] Tweak and implement svg.clock.js (see additional info)

### Standard Task List

- [ ] Write BDD scenarios
- [ ]  Write Unit tests
- [ ]  Run Unit tests
- [ ]  Manual Test
- [ ] UI/UX Signoff
- [ ]  Content Signoff
- [ ]  Check DoD

### Additional Info

- Designs [here](https://drive.google.com/a/ustwo.com/folderview?id=0B7rd_E0EdjoCfl81NlNnb29rcGpoMkpYcWI1ZnZTdFgtcTNpMW1WZEtzWUhacHlreVY0ZW8&usp=sharing)
- Open source library for [SVG clocks](https://github.com/wout/svg.clock.js) OR we can use CSS like [this](https://css-tricks.com/css3-clock/), [this](http://www.javascriptkit.com/dhtmltutors/css3clock.shtml) or [this](https://cssanimation.rocks/clocks/)

**Comment by andydutch** [comment]
See funky example from Apple here: http://www.apple.com/macbook-air/
