### ISSUE TITLE
Search spinner

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#315]
Right now the magnifying glass icon next to blog categories dropdown isn't entirely clear for some users, so we should have a review and see how can we improve clarity.

**Comment by daaain** [comment]
Gyppsy won't be available until Monday 23rd, blocking.

**Comment by matthewedwards12** [comment]
petra to pick up. Matthew to talk to Gyppsy about design.

**Comment by matthewedwards12** [comment]
Grant to look at animations across the whole search function

**Comment by matthewedwards12** [comment]
Grant working on new spinner
