### ISSUE TITLE
Make site work without Javascript

### ISSUE THREAD

**Issue by daaain** [ustwo/ustwo.com-frontend#348]
We're nearly there with the site working without any Javascript at all, so maybe we could do the final push to be able to talk about it. The purpose is to make sure we're good even with aggressive ad blockers, that assistive services have some default interaction to fall back to in case JS solutions don't work and to have deep / direct shareable URLs.

Some of it are relatively simple CSS defaults, some are a bit more work on React side.

Outstanding issues / solutions:
- Load title font locally instead of Typekit (and have fallback for Localfont)
- Make mobile menu a separate page or always visible
- Make studio details always open in footer on mobile
- Make job listings open Workable page directly (and maybe hide the `+`)
- Make blog search and category selection submit as form (and categories to have their own URLs)
- Add pagination to blog or link to full archive
- Make Google Analytics work with JS (http://www.simoahava.com/analytics/track-non-javascript-visits-google-analytics/)

**Comment by collingo** [comment]
All great suggestions Dain. I would suggest opening all jobs listings might make the join us page quite a heavy request. Opening would require the server to request the full details of every job listing. Might be an idea to make the collapsed job item a direct link to the Workable page (like we do with the 'Read full description' page)?

**Comment by daaain** [comment]
That's actually a much better idea, updated the list, thanks Nick!

**Comment by daaain** [comment]
Actually, this should also increase crawlability, I've been experimenting with a simple crawler as a method to warm the CDN cache up and apparently right now the only blog posts crawled are the ones on the first page of blog index. Here's the full list of pages a crawler can discover on their own:  https://www.apifier.com/crawlers/BJ8bebc956mHyX8yG/execs/gcuIpqoEQ683vugdJ/results

**Comment by matthewedwards12** [comment]
@andydutch this is related to the mobile menu nav 'not working' when you have content blockers on.

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
