### ISSUE TITLE
PPP download source change

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#374]

**Comment by matthewedwards12** [comment]
At present PPP is being downloaded from my dropbox account. We need to re-redirect the request so the PPP docs are taken from the CDN server (the original source). 

Your NGINX server returns a 504 Gateway Time-Out while accessing this link : http://cdn.ustwo.com/PPP/PP3.pdf
( or this link : http://cdn.ustwo.com/PPP/PP3.ibooks )
( or this link : http://cdn.ustwo.com/PPP/PP3_Extras.zip )

**Comment by andydutch** [comment]
Linked to from here: https://ustwo.com/blog/the-ustwo-pixel-perfect-precision-handbook-3/
