### ISSUE TITLE
Add canonical link code to pages

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#377]

**Comment by matthewedwards12** [comment]
So we can repost some of our content, we'd like to have a rel=canonical link code added where appropriate. PProbably needs some discussion.
Been reading, amongst other stuff – https://moz.com/learn/seo/canonicalization

**Comment by andydutch** [comment]
* Is there SEO value in this?
* ustwo are to repost some content elsewhere - such as Medium

**Comment by matthewedwards12** [comment]
from what I understand, you'd need to add the canonical link tag to the secondary posting – and have it link back to the original. Not so helpful if we're reposting on Medium where that is not an option.

**Comment by andydutch** [comment]
This would require adding at source, which cannot be done at Medium for example.

Closed.
