### ISSUE TITLE
Plus Sign Icons on Jobs Page broken

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#385]

**Comment by matthewedwards12** [comment]
https://drive.google.com/open?id=0B5YUpSnTZn51ZVlpdWNjY2E2Sjg

the plus signs are looking weird... Out of alignment.

**Comment by andydutch** [comment]
Non-retina only?

**Comment by andydutch** [comment]
Chrome @certain zooms.
