### ISSUE TITLE
Subscribe to ustwo blog

### ISSUE THREAD

**Issue by marleypetropoulos** [ustwo/ustwo.com-frontend#401]
As a user...
I want... subscribe to follow the ustwo blog
So that...

Knowns (ACs)
Unknowns (Questions)

**Comment by marleypetro** [comment]
speak to Elementary to find out best solution for RSS on blog

**Comment by matthewedwards12** [comment]
Chris to deploy and document

**Comment by voylinux** [comment]
Did you notice that this way your feed is pointing to your wp subdomain?

The problem is if they click or try to share the content from their rss reader, they will link to a blank page.

**Comment by daaain** [comment]
Hmm, we could eventually use the URL https://ustwo.com/api/feed/ instead as WP is proxied by nginx there, however this is broken right now as currently WP echoes back the internal nginx host alias http://backend.

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
