### ISSUE TITLE
Add a "no filter" option to blog post images

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#415]

**Comment by matthewedwards12** [comment]
currently we have a dark filter applied to every hero/featured image shown on an individual blog.
Make the filter overlay optional so that we can select "no filter" within the blog editing page.

**Comment by andydutch** [comment]
* Remove overlay entirely
* Add option to select nav/logo colour

**Comment by phil-linnell** [comment]
Is there an option to make the decision about white or black navigation automated?
