### ISSUE TITLE
Custom field for blog excerpts

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#416]

**Comment by matthewedwards12** [comment]
add an optional custom field for the excerpt/preview text on a blog post, so that the hub page does not show just the first chunk of text.

AC:
Field is available on each blog editing page
Field is optional
If not filled in, the fallback position means first section of text is used (as currently)

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
