### ISSUE TITLE
Issue with modals when using adblocker

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#420]

**Comment by matthewedwards12** [comment]
Pointed out on Twitter on 9th. Using Crystal on iOS means that the Mobile Nav crashes the site. Needs investigation...

**Comment by daaain** [comment]
We might have to bite the bullet and go for a no Javascript baseline functionality as discussed in #348.

For the mobile menu in particular we could have it on a separate page / URL or be always shown when JS is disabled.

**Comment by andydutch** [comment]
Could using a fixed nav in the footer, perhaps icon based, work? or a menu that disappears on scroll down but reappears on scroll up (like Facebook's native app)

**Comment by daaain** [comment]
This looks interesting: http://blog.christopherianmurphy.com/2016/01/responsive-pure-css-menu.html

**Comment by chriswatts91** [comment]
Looks to be an issue with the react-transition-manager library. Crystal looks to be blocking `div.shown`. 
I've temporarily removed shown from the modal as it doesn't seem to have been used and have opened an issue here: https://github.com/collingo/react-transition-manager/issues/6

**Comment by andydutch** [comment]
@chriswatts91, can you make a pull request with the fix? 

If he doesn't merge it, we can fork it.

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
