### ISSUE TITLE
Image block needs to support animated Gifs

### ISSUE THREAD

**Issue by andydutch** [ustwo/ustwo.com-frontend#429]
Gifs are currently supported in the Text module, but not in the Image module.

**Comment by chriswatts91** [comment]
The image module supports gifs though there is a minimum size requirement of 1024px × 768px

**Comment by andydutch** [comment]
The issue seems to be that when the animated gif is resized on upload, only the first screen of the gif gets resized - essentially turning into a non animated gif.
