### ISSUE TITLE
Fix h4 headers in blog

### ISSUE THREAD

**Issue by phil-linnell** [ustwo/ustwo.com-frontend#431]
had one other thing I wanted you to look at – the gap between headers and paragraph text
[5:44 PM] 
to me this looks wrong:
https://ustwo.com/blog/more-universal-apps
(More) Universal Apps
Creating a universal app that runs on both iOS and tvOS with a unified code base

[5:46 PM] 
and – most importantly – if we fixed that then the older blog posts that we want to convert to use modules would look ok too!

**Comment by matthewedwards12** [comment]
I think this needs a designer to look at properly. But – we ought to add a quick fix.

H3 needs to be Title case PX Grotesk (ie body copy font) in *bold*. 30px and line height 30px.

@andydutch
