### ISSUE TITLE
Look into screen heights and placement of chevron

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#458]
The animated chevron indicating more content is hidden on mobile (iOS, iPhone 6) by the OS navigation bar.

**Comment by phil-linnell** [comment]
Yeah this was an issue I always wanted to fix back in the day. Unfortunately this is essentially a browser problem, mainly on iOS Safari I think. The chevron is positioned relative to the bottom of the initial rendered view (100vh in css). But the chrome of the browser overlays this and covers up the chevron.

This article explains the point in detail: http://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html

There is a potential fix/hack: https://github.com/rodneyrehm/viewport-units-buggyfill
but I'm wary of using such things. 

I will look into it more.

**Comment by phil-linnell** [comment]
@matthewedwards12 Get design input

**Comment by matthewedwards12** [comment]
no longer blocked
