### ISSUE TITLE
Punctuation encoding in Header module

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#489]
https://ustwo.com/events/a-conversation-with-leslie-muller-the-evolution-of-wearables

Lands End case study. 

Takeovers. 
Punctuation not displaying correctly in certain modules – examples above

**Comment by chriswatts91** [comment]
See https://github.com/ustwo/ustwo.com-frontend/issues/542

**Comment by phil-linnell** [comment]
From Casey "Using an apostrophe in a blog post title breaks it, replacing the apostrophe with ̻"

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
