### ISSUE TITLE
Events page header copy illegible on mobile

### ISSUE THREAD

**Issue by marleypetropoulos** [ustwo/ustwo.com-frontend#513]
Legibility of events page header copy is poor on mobile.

![screen shot 2016-04-25 at 20 04 33](https://cloud.githubusercontent.com/assets/6105662/14795655/5572c144-0b21-11e6-9fc8-890b1fd0e8ad.png)

**Comment by matthewedwards12** [comment]
look for another image/crop?

**Comment by matthewedwards12** [comment]
removing pic
