### ISSUE TITLE
In page Google Analytics not working

### ISSUE THREAD

**Issue by andydutch** [ustwo/ustwo.com-frontend#515]
We didn't find a tracking snippet on your site. In-Page Analytics cannot load. Please make sure you have tracking installed correctly. If your snippet is included in a separate JavaScript file, you'll have to manually check it is being loaded correctly.
You can try the Page Analytics Chrome Extension which has almost identical functionality to the In-Page Analytics report, but can often resolve these issues

**Comment by matthewedwards12** [comment]
I think this will sort out the issue

https://support.google.com/analytics/answer/2558867?hl=en-GB&utm_id=ad

In page analytics requires amendment to the snippet.

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
