### ISSUE TITLE
Open Graph Weirdness

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#526]

**Comment by matthewedwards12** [comment]
See error messages https://drive.google.com/open?id=0B5YUpSnTZn51b1d5OEt3aUwtMWc

Home page Open Graph data is missing, but it looks to me as though it is in place. Any thoughts @andydutch ?

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
