### ISSUE TITLE
Font loading order

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#529]

**Comment by matthewedwards12** [comment]
@chriswatts91 Andy told me you'd looked into the font loading problem – ie when we see default fonts for a split second before the page loads fully and renders the correct font. Please could you share findings/thoughts in the usweb Slack channel at some point?

**Comment by matthewedwards12** [comment]
investigate self host license

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
