### ISSUE TITLE
Page fails to load

### ISSUE THREAD

**Issue by adamtaylo** [ustwo/ustwo.com-frontend#531]
@matthewedwards12 pretty major bug here on ustwo.com

Device/OS - iPhone 6 iOS 9.3.2

Open Safari
Go to ustwo.com
Tap the hamburger in top right
Watch the menu load for a split second
See that the page fails to load and the user is left with a blank screen

I can reproduce this 100% of the time.

**Comment by matthewedwards12** [comment]
@adamtaylo do you have content blockers enabled? It's probably that :)

**Comment by matthewedwards12** [comment]
you can reload without blockers if you hold the reload icon

**Comment by matthewedwards12** [comment]
covered elsewhere
