### ISSUE TITLE
Add new url for ustwo manifesto

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#532]

**Comment by matthewedwards12** [comment]
we have a PDF of the ustwo manifesto that we'd like to add as a link to the Join Us page. 

We'd want ustwo.com/manifesto (or similar) set up to 'host' it

**Comment by matthewedwards12** [comment]
Agreed to create template page and produce URL as needed. Assumption is that we'd use 2-3 of these. PPP/Manifesto/Press page

**Comment by chriswatts91** [comment]
To make use of Wordpress permalinks

**Comment by chriswatts91** [comment]
To setup generic page template on frontend, enabling Matthew to create pages in the backend leaving ED to set up the frontend routing

**Comment by andydutch** [comment]
@chriswatts91, the template currently used for the blog pages is sufficient.

Removing the:

* Author + date from the header
* More juice section
* Social share 
* About the author

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
