### ISSUE TITLE
Blog post apostrophe "special characters" issue

### ISSUE THREAD

**Issue by caseyhopkins** [ustwo/ustwo.com-frontend#542]
Using an apostrophe in a blog post title breaks it, replacing the apostrophe with &#827;

**Comment by matthewedwards12** [comment]
also see 489

**Comment by matthewedwards12** [comment]
@andydutch possibly related to key used to input the character? There are two options to do this, 1 using the 'regular' key above the question mark and 2, using alt+]

**Comment by chriswatts91** [comment]
Unable to replicate both locally and in production. Will keep an eye on it.

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
