### ISSUE TITLE
Create option to include multiple authors in a blog biog

### ISSUE THREAD

**Issue by matthewedwards12** [ustwo/ustwo.com-frontend#545]

**Comment by andydutch** [comment]
Four columns per row, centre aligned if there's less than four on one row.

**Comment by andydutch** [comment]
If there's one author, show the name at the top and in the archive. 

If there's multiple, ability to select the 'primary one to show'

**Comment by phil-linnell** [comment]
Andy and Phil looked at this and there is a valid issue with ellipsis inside flexbox. Further investigation needed.
http://stackoverflow.com/questions/37870674/css-ellipsis-in-middle-using-flexbox-breaks-in-safari

**Comment by phil-linnell** [comment]
Closed as reassigning to new issue tracker.
