### ISSUE TITLE
Problem with make compiler-build build.

### ISSUE THREAD

**Issue by diegovilarinho** [ustwo/ustwo.com-frontend#553]
I'm running `make compiler-build build` and return me this error:
`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/Applications/MAMP/htdocs/diegovilarinho/site/ustwo/ustwo.com-frontend/package.compiler.json\\\\\\\" to rootfs \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/df1c6b2dd40849f9609af2e164c97b1e3cf110aa1fc79e0cff420d857a1f14ea\\\\\\\" at \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/df1c6b2dd40849f9609af2e164c97b1e3cf110aa1fc79e0cff420d857a1f14ea/home/ustwo/package.json\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n".`

**Comment by arnau** [comment]
Hello @diegovilarinho sorry for the delay, could you give us some more context? e.g. Docker version, macOS version, and any other contextual info you think might help us help you?
