### ISSUE TITLE
Which Licence?

### ISSUE THREAD

**Issue by tgrrr** [ustwo/ustwo.com-frontend#555]
Hi,

The licence reads both Copyright and GNU. Mind if I double-check which licence it is?

Cheers, Phil

> # License
>
> ustwo.com website front end and tools Copyright (C) 2015 ustwo
> 
> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
> 
> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
> 
> You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.

**Comment by daaain** [comment]
Hey Phil,

It's both :) Without going into the legal details, copyright is not mutually exclusive with GPL, we're in fact just using the boilerplate licence.

See http://www.gnu.org/licenses/gpl.html and scroll down to "How to Apply These Terms to Your New Programs".

Have a nice day,
dain

**Comment by tgrrr** [comment]
Facepalm. I've spent way too much time looking at licences recently.

Thanks. And kudos.
Phil
