### ISSUE TITLE
How is the page background colour changed?

### ISSUE THREAD

**Issue by tttwb** [ustwo/ustwo.com-frontend#560]
In the page background 

```
<article class="page-home add show shown" style="background-color: rgb(97, 20, 204);">
```

How does the rgb value change smoothly as you scroll down the page?

I've looked through the code but cannot find the javascript that achieves this.

Thank you

**Comment by ch2ch3** [comment]
Hey @tttwb, we were using a library called [scrollmagic](https://github.com/janpaepke/ScrollMagic) for that.

You can find the relevant code here: https://github.com/ustwo/ustwo.com-frontend/blob/master/src/app/components/home/index.js#L43-L77
